apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mjabji1uq-nodejs
  janus-idp.io/tekton: mjabji1uq-nodejs
  backstage.io/kubernetes-id: mjabji1uq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mjabji1uq-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
