apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mjabji1uq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mjabji1uq-nodejs 
  name: mjabji1uq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mjabji1uq-nodejs 
